create table if not exists public.telemetry_events (
  id bigint generated by default as identity primary key,
  client_key text not null,
  event_type text not null,
  status text,
  created_at timestamptz not null default now()
);

alter table public.telemetry_events enable row level security;

create policy "Telemetry insert" on public.telemetry_events
  for insert
  with check (true);
